language: python
install:
- pip install mkdocs-material pygments mkdocs-redirects
script:
- mkdocs build --verbose --clean
deploy:
 provider: pages
 cleanup: false
 github_token: $GITHUB_TOKEN
 local_dir: site
 name: $BOT_NAME
 email: $BOT_EMAIL
 on:
   branch: master
