site_name: "mailcow: dockerized documentation"
repo_url: https://github.com/mailcow/mailcow-dockerized
#remote_branch: gh-pages
#theme: material
#extra:
#  palette:
#    primary: 'indigo'
#    accent: 'yellow'
#  logo: 'images/logo.svg'

#markdown_extensions:
#  - admonition
#  - codehilite(guess_lang=true)
#  - footnotes
#  - meta
#  - toc(permalink=true)

pages:
    - 'About mailcow: dockerized': 'index.md'
    - 'Installation': 'install.md'
    - 'First Steps': 'first_steps.md'
    - 'Usage & Examples': 'u_and_e.md'
