site_name: 'mailcow: dockerized documentation'
site_url: https://mailcow.github.io/mailcow-dockerized-docs/
copyright: "Copyright &copy; 2022 Servercow Team & Community<br>Based on the work from André Peters"
repo_name: mailcow/mailcow-dockerized
repo_url: https://github.com/mailcow/mailcow-dockerized
edit_uri: ../mailcow-dockerized-docs/edit/master/docs/
remote_branch: gh-pages

theme:
  name: material
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.png

plugins:
  - search
  - i18n:
      default_language: en
      languages:
        en: English
        de: Deutsch

markdown_extensions:
  - attr_list
  - admonition
  - toc:
      permalink: true
