site_name: "mailcow: dockerized documentation"
repo_url: https://github.com/mailcow/mailcow-dockerized
remote_branch: gh-pages
theme: material
markdown_extensions:
  - codehilite(guess_lang=true)
  - toc(permalink=true)
  - admonition
  - pymdownx.magiclink
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.mark
  - pymdownx.tilde
pages:
- 'Information & Support': 'index.md'
- 'Prerequisites':
  - 'Prepare Your System': 'requirements.md'
  - 'DNS Setup': 'dns.md'
- 'Migrating from mailcow 0.14': 'mc14_import.md'
- 'Installation & Update':
  - 'Installation': 'install.md'
  - 'Update': 'update.md'
- 'First Steps (optional)': 
  - 'SSL': 'ssl.md'
  - 'Rspamd Web UI': 'rspamd_ui.md'
  - 'Reverse Proxy': 'rp.md'
  - 'Setup a relayhost': 'relayhost.md'
  - 'Log to Syslog': 'syslog.md'
  - 'Local MTA on Docker host': 'local_mta.md'
  - 'Sender and receiver model': 'sender_rcv.md'
- 'Usage & Examples':
  - 'Debugging & Troubleshooting': 'debug.md'
  - 'mailcow UI Configuration': 'mailcow_ui.md'
  - 'Redis': 'redis.md'
  - 'MySQL': 'mysql.md'
  - 'Rspamd': 'rspamd.md'
  - 'Why bind9?': 'why_bind9.md'
  - 'Adjust Service Configurations': 'change_config.md'
  - 'Customize Dockerfiles': 'cust_dockerfiles.md'
  - 'Docker Compose Bash Completion': 'dc_bash_compl.md'
  - 'Backup Maildir': 'backup_maildir.md'
  - 'Two-Factor Authentication': 'tfa.md'
  - 'Redirect HTTP to HTTPS': '80_to_443.md'
  - 'Anonymize Headers': 'anonym_headers.md'
  - 'Tagging': 'tagging.md'
  - 'Blacklist / Whitelist': 'bl_wl.md'
  - 'Autodiscover / Autoconfig': 'autodiscover_config.md'
  - 'Disable Sender Addresses Verification': 'disable_sender_verification.md'
- 'Third party apps':
  - 'Roundcube': 'roundcube.md'
  - 'Portainer': 'portainer.md'
  - 'Gogs': 'gogs.md'
extra:
  logo: 'images/logo.svg'
  palette:
    primary: 'indigo'
    accent: 'orange'
extra_css: [extra.css]
